In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

In [2]:
# Extract Divvy Files
Divvy_Trips_2017_Q4_file = "Divvy_Trips_2017_Q4.csv"
Divvy_Trips_2017_Q3_file = "Divvy_Trips_2017_Q3.csv"
Divvy_Trips_2017_Q2_file = "Divvy_Trips_2017_Q2.csv"
Divvy_Trips_2017_Q1_file = "Divvy_Trips_2017_Q1.csv"
Divvy_Trips_2016_Q4_file = "Divvy_Trips_2016_Q4.csv"
Divvy_Trips_2016_Q3_file = "Divvy_Trips_2016_Q3.csv"
Divvy_Stations_2017_Q3Q4_file = "Divvy_Stations_2017_Q3Q4.csv"
Divvy_Stations_2017_Q1Q2_file = "Divvy_Stations_2017_Q3Q4.csv"
Divvy_Stations_2016_Q4_file = "Divvy_Stations_2016_Q4.csv"
Divvy_Stations_2016_Q3_file = "Divvy_Stations_2016_Q3.csv"

In [3]:
# Read each Divvy Data File and store into Pandas DataFrame
Divvy_Trips_2017_Q4_df = pd.read_csv(Divvy_Trips_2017_Q4_file)
Divvy_Trips_2017_Q3_df = pd.read_csv(Divvy_Trips_2017_Q3_file)
Divvy_Trips_2017_Q2_df = pd.read_csv(Divvy_Trips_2017_Q2_file)
Divvy_Trips_2017_Q1_df = pd.read_csv(Divvy_Trips_2017_Q1_file)
Divvy_Trips_2016_Q4_df = pd.read_csv(Divvy_Trips_2016_Q4_file)
Divvy_Trips_2016_Q3_df = pd.read_csv(Divvy_Trips_2016_Q3_file)

Divvy_Stations_2017_Q3Q4_df = pd.read_csv(Divvy_Stations_2017_Q3Q4_file)
Divvy_Stations_2017_Q1Q2_df = pd.read_csv(Divvy_Stations_2017_Q1Q2_file)
Divvy_Stations_2016_Q4_df = pd.read_csv(Divvy_Stations_2016_Q4_file)
Divvy_Stations_2016_Q3_df = pd.read_csv(Divvy_Stations_2016_Q3_file)

In [4]:
# Combine Trips Divvy Data File and store into Pandas DataFrame
Divvy_Trips_2017_Q3Q4_df = Divvy_Trips_2017_Q4_df.append(Divvy_Trips_2017_Q3_df)
Divvy_Trips_2017_Q2Q3Q4_df = Divvy_Trips_2017_Q3Q4_df.append(Divvy_Trips_2017_Q2_df)
Divvy_Trips_2017_df = Divvy_Trips_2017_Q2Q3Q4_df.append(Divvy_Trips_2017_Q1_df)
#Divvy_Trips_2017_df.head()
Divvy_Trips_2016_df = Divvy_Trips_2016_Q3_df.append(Divvy_Trips_2016_Q4_df)
Divvy_Trips_df = Divvy_Trips_2017_df.append(Divvy_Trips_2016_df)
Divvy_Trips_df.head()

/Users/michelelodl/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

,bikeid,birthyear,end_time,from_station_id,from_station_name,gender,start_time,starttime,stoptime,to_station_id,to_station_name,trip_id,tripduration,usertype
0,3304,1988.0,1/1/2018 0:03,159,Claremont Ave & Hirsch St,Male,12/31/2017 23:58,NaN,NaN,69,Damen Ave & Pierce Ave,17536701,284,Subscriber
1,5975,NaN,1/1/2018 0:18,145,Mies van der Rohe Way & Chestnut St,NaN,12/31/2017 23:54,NaN,NaN,145,Mies van der Rohe Way & Chestnut St,17536700,1402,Customer
2,4906,NaN,1/1/2018 0:18,145,Mies van der Rohe Way & Chestnut St,NaN,12/31/2017 23:54,NaN,NaN,145,Mies van der Rohe Way & Chestnut St,17536699,1441,Customer
3,5667,1963.0,12/31/2017 23:53,340,Clark St & Wrightwood Ave,Male,12/31/2017 23:48,NaN,NaN,143,Sedgwick St & Webster Ave,17536698,315,Subscriber
4,5353,1977.0,12/31/2017 23:47,240,Sheridan Rd & Irving Park Rd,Male,12/31/2017 23:42,NaN,NaN,245,Clarendon Ave & Junior Ter,17536697,272,Subscriber

In [5]:
Divvy_Trips_df

,bikeid,birthyear,end_time,from_station_id,from_station_name,gender,start_time,starttime,stoptime,to_station_id,to_station_name,trip_id,tripduration,usertype
0,3304,1988.0,1/1/2018 0:03,159,Claremont Ave & Hirsch St,Male,12/31/2017 23:58,NaN,NaN,69,Damen Ave & Pierce Ave,17536701,284,Subscriber
1,5975,NaN,1/1/2018 0:18,145,Mies van der Rohe Way & Chestnut St,NaN,12/31/2017 23:54,NaN,NaN,145,Mies van der Rohe Way & Chestnut St,17536700,1402,Customer
2,4906,NaN,1/1/2018 0:18,145,Mies van der Rohe Way & Chestnut St,NaN,12/31/2017 23:54,NaN,NaN,145,Mies van der Rohe Way & Chestnut St,17536699,1441,Customer
3,5667,1963.0,12/31/2017 23:53,340,Clark St & Wrightwood Ave,Male,12/31/2017 23:48,NaN,NaN,143,Sedgwick St & Webster Ave,17536698,315,Subscriber
4,5353,1977.0,12/31/2017 23:47,240,Sheridan Rd & Irving Park Rd,Male,12/31/2017 23:42,NaN,NaN,245,Clarendon Ave & Junior Ter,17536697,272,Subscriber
5,5840,1988.0,12/31/2017 23:51,93,Sheffield Ave & Willow St,Male,12/31/2017 23:41,NaN,NaN,343,Racine Ave & Wrightwood Ave,17536696,589,Subscriber
6,6351,1990.0,12/31/2017 23:39,337,Clark St & Chicago Ave,Male,12/31/2017 23:34,NaN,NaN,182,Wells St & Elm St,17536695,301,Subscriber
7,2562,1987.0,12/31/2017 23:23,226,Racine Ave & Belmont Ave,Male,12/31/2017 23:21,NaN,NaN,117,Wilton Ave & Belmont Ave,17536694,141,Subscriber
8,2471,1981.0,12/31/2017 23:27,49,Dearborn St & Monroe St,Male,12/31/2017 23:17,NaN,NaN,26,McClurg Ct & Illinois St,17536693,615,Subscriber
9,6462,1980.0,12/31/2017 23:09,196,Cityfront Plaza Dr & Pioneer Ct,Male,12/31/2017 22:57,NaN,NaN,255,Indiana Ave & Roosevelt Rd,17536692,743,Subscriber
10,3775,1991.0,12/31/2017 22:53,59,Wabash Ave & Roosevelt Rd,Male,12/31/2017 22:50,NaN,NaN,72,Wabash Ave & 16th St,17536691,216,Subscriber
11,3663,1990.0,12/31/2017 22:53,59,Wabash Ave & Roosevelt Rd,Female,12/31/2017 22:50,NaN,NaN,72,Wabash Ave & 16th St,17536690,202,Subscriber
12,6456,1991.0,12/31/2017 22:55,475,Washtenaw Ave & Lawrence Ave,Male,12/31/2017 22:48,NaN,NaN,242,Damen Ave & Leland Ave,17536689,420,Subscriber
13,5529,1986.0,12/31/2017 22:51,67,Sheffield Ave & Fullerton Ave,Male,12/31/2017 22:45,NaN,NaN,166,Ashland Ave & Wrightwood Ave,17536688,397,Subscriber
14,3536,1988.0,12/31/2017 22:44,123,California Ave & Milwaukee Ave,Male,12/31/2017 22:42,NaN,NaN,259,California Ave & Francis Pl,17536687,137,Subscriber
15,3644,1961.0,12/31/2017 22:20,523,Eastlake Ter & Rogers Ave,Male,12/31/2017 22:09,NaN,NaN,447,Glenwood Ave & Morse Ave,17536686,677,Subscriber
16,2928,1992.0,12/31/2017 22:27,196,Cityfront Plaza Dr & Pioneer Ct,Male,12/31/2017 22:07,NaN,NaN,626,Delano Ct & Roosevelt Rd,17536685,1200,Subscriber
17,5889,1977.0,12/31/2017 22:12,293,Broadway & Wilson Ave,Male,12/31/2017 22:05,NaN,NaN,245,Clarendon Ave & Junior Ter,17536684,399,Subscriber
18,5960,1992.0,12/31/2017 22:11,510,Spaulding Ave & Division St,Male,12/31/2017 21:57,NaN,NaN,260,Kedzie Ave & Milwaukee Ave,17536683,845,Subscriber
19,3079,1988.0,12/31/2017 21:44,304,Broadway & Waveland Ave,Male,12/31/2017 21:42,NaN,NaN,232,Pine Grove Ave & Waveland Ave,17536680,86,Subscriber
20,1619,1990.0,12/31/2017 21:39,149,Calumet Ave & 33rd St,Male,12/31/2017 21:35,NaN,NaN,148,State St & 33rd St,17536675,263,Subscriber
21,5926,1977.0,12/31/2017 21:39,123,California Ave & Milwaukee Ave,Male,12/31/2017 21:34,NaN,NaN,290,Kedzie Ave & Palmer Ct,17536672,327,Subscriber
22,2928,1992.0,12/31/2017 21:49,211,St. Clair St & Erie St,Male,12/31/2017 21:33,NaN,NaN,196,Cityfront Plaza Dr & Pioneer Ct,17536671,969,Subscriber
23,3783,1995.0,12/31/2017 21:31,320,Loomis St & Lexington St,Male,12/31/2017 21:25,NaN,NaN,22,May St & Taylor St,17536653,339,Subscriber
24,4581,1964.0,12/31/2017 21:28,26,McClurg Ct & Illinois St,Male,12/31/2017 21:21,NaN,NaN,7,Field Blvd & South Water St,17536647,393,Subscriber
25,5667,1963.0,12/31/2017 21:22,143,Sedgwick St & Webster Ave,Male,12/31/2017 21:17,NaN,NaN,340,Clark St & Wrightwood Ave,17536645,303,Subscriber
26,3696,1989.0,12/31/2017 21:22,124,Damen Ave & Cullerton St,Male,12/31/2017 21:17,NaN,NaN,129,Blue Island Ave & 18th St,17536644,318,Subscriber
27,6189,NaN,12/31/2017 21:57,176,Clark St & Elm St,NaN,12/31/2017 21:16,NaN,NaN,37,Dearborn St & Adams St,17536643,2489,Customer
28,3777,1977.0,12/31/2017 21:10,91,Clinton St & Washington Blvd,Male,12/31/2017 21:08,NaN,NaN,66,Clinton St & Lake St,17536642,121,Subscriber
29,2928,1992.0,12/31/2017 21:33,46,Wells St & Walton St,Male,12/31/2017 21:05,NaN,NaN,211,St. Clair St & Erie St,17536641,1662,Subscriber
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683802,5249,1989.0,NaN,260,Kedzie Ave & Milwaukee Ave,Female,NaN,10/1/2016 00:11:02,10/1/2016 00:22:48,160,Campbell Ave & North Ave,12150195,706,Subscriber
683803,4293,1972.0,NaN,130,Damen Ave & Division St,Male,NaN,10/1/2016 00:10:13,10/1/2016 00:27:50,230,Lincoln Ave & Roscoe St,12150194,1057,Subscriber
683804,883,1973.0,NaN,115,Sheffield Ave & Wellington Ave,Male,NaN,10/1/2016 00:10:13,10/1/2016 00:27:44,301,Clark St & Schiller St,12150193,1051,Subscriber
683805,2483,1986.0,NaN,4,Burnham Harbor,Male,NaN,10/1/2016 00:10:01,10/1/2016 00:37:24,121,Blackstone Ave & Hyde Park Blvd,12150191,1643,Subscriber
683806,381,1988.0,NaN,88,May St & Randolph St,Male,NaN,10/1/2016 00:09:55,10/1/2016 00:17:08,192,Canal St & Adams St,12150190,433,Subscriber
683807,4606,1988.0,NaN,190,Southport Ave & Wrightwood Ave,Male,NaN,10/1/2016 00:09:35,10/1/2016 00:16:23,144,Larrabee St & Webster Ave,12150189,408,Subscriber
683808,2079,1989.0,NaN,332,Halsted St & Diversey Pkwy,Male,NaN,10/1/2016 00:09:23,10/1/2016 00:23:32,224,Halsted St & Willow St,12150188,849,Subscriber
683809,490,1992.0,NaN,144,Larrabee St & Webster Ave,Male,NaN,10/1/2016 00:09:18,10/1/2016 00:19:42,152,Lincoln Ave & Diversey Pkwy,12150187,624,Subscriber
683810,2515,1988.0,NaN,181,LaSalle St & Illinois St,Male,NaN,10/1/2016 00:08:10,10/1/2016 00:17:44,36,Franklin St & Jackson Blvd,12150185,574,Subscriber
683811,5360,1967.0,NaN,128,Damen Ave & Chicago Ave,Female,NaN,10/1/2016 00:08:06,10/1/2016 00:11:23,183,Damen Ave & Augusta Blvd,12150184,197,Subscriber
683812,5172,1982.0,NaN,147,Indiana Ave & 26th St,Male,NaN,10/1/2016 00:06:47,10/1/2016 00:17:34,168,Michigan Ave & 14th St,12150182,647,Subscriber
683813,2019,1989.0,NaN,181,LaSalle St & Illinois St,Male,NaN,10/1/2016 00:06:24,10/1/2016 00:18:24,331,Halsted St & Blackhawk St (*),12150181,720,Subscriber
683814,957,1991.0,NaN,515,Paulina St & Howard St,Female,NaN,10/1/2016 00:05:48,10/1/2016 00:12:48,514,Ridge Blvd & Howard St,12150180,420,Subscriber
683815,4134,1991.0,NaN,120,Wentworth Ave & Archer Ave,Female,NaN,10/1/2016 00:05:15,10/1/2016 00:19:39,280,Morgan St & 31st St,12150179,864,Subscriber
683816,811,1994.0,NaN,349,Halsted St & Wrightwood Ave,Female,NaN,10/1/2016 00:05:09,10/1/2016 00:13:25,93,Sheffield Ave & Willow St,12150178,496,Subscriber
683817,710,1990.0,NaN,69,Damen Ave & Pierce Ave,Male,NaN,10/1/2016 00:04:41,10/1/2016 00:10:45,17,Wood St & Division St,12150177,364,Subscriber
683818,1691,1988.0,NaN,511,Albany Ave & Bloomingdale Ave,Female,NaN,10/1/2016 00:04:12,10/1/2016 00:12:22,260,Kedzie Ave & Milwaukee Ave,12150176,490,Subscriber
683819,4182,1983.0,NaN,359,Larrabee St & Division St,Male,NaN,10/1/2016 00:04:02,10/1/2016 00:16:16,126,Clark St & North Ave,12150175,734,Subscriber
683820,5470,1988.0,NaN,44,State St & Randolph St,Male,NaN,10/1/2016 00:03:34,10/1/2016 00:13:01,134,Peoria St & Jackson Blvd,12150174,567,Subscriber
683821,4514,1993.0,NaN,117,Wilton Ave & Belmont Ave,Male,NaN,10/1/2016 00:03:28,10/1/2016 00:10:45,349,Halsted St & Wrightwood Ave,12150173,437,Subscriber
683822,404,1995.0,NaN,426,Ellis Ave & 60th St,Male,NaN,10/1/2016 00:03:20,10/1/2016 00:08:16,248,Woodlawn Ave & 55th St,12150172,296,Subscriber
683823,732,NaN,NaN,68,Clinton St & Tilden St,NaN,NaN,10/1/2016 00:02:59,10/1/2016 00:28:14,199,Wabash Ave & Grand Ave,12150171,1515,Customer
683824,4290,NaN,NaN,68,Clinton St & Tilden St,NaN,NaN,10/1/2016 00:02:26,10/1/2016 00:28:22,199,Wabash Ave & Grand Ave,12150170,1556,Customer
683825,2288,1990.0,NaN,287,Franklin St & Monroe St,Male,NaN,10/1/2016 00:01:57,10/1/2016 00:06:43,68,Clinton St & Tilden St,12150169,286,Subscriber
683826,2561,NaN,NaN,68,Clinton St & Tilden St,NaN,NaN,10/1/2016 00:01:24,10/1/2016 00:28:06,199,Wabash Ave & Grand Ave,12150166,1602,Customer
683827,3999,1991.0,NaN,56,Desplaines St & Kinzie St,Female,NaN,10/1/2016 00:01:08,10/1/2016 00:04:42,133,Kingsbury St & Kinzie St,12150165,214,Subscriber
683828,2483,1986.0,NaN,255,Indiana Ave & Roosevelt Rd,Male,NaN,10/1/2016 00:00:58,10/1/2016 00:09:33,4,Burnham Harbor,12150164,515,Subscriber
683829,3892,1990.0,NaN,56,Desplaines St & Kinzie St,Male,NaN,10/1/2016 00:00:41,10/1/2016 00:04:19,133,Kingsbury St & Kinzie St,12150163,218,Subscriber
683830,3567,1987.0,NaN,298,Lincoln Ave & Belle Plaine Ave,Female,NaN,10/1/2016 00:00:32,10/1/2016 00:16:02,460,Clark St & Bryn Mawr Ave,12150162,930,Subscriber
683831,5320,NaN,NaN,298,Lincoln Ave & Belle Plaine Ave,NaN,NaN,10/1/2016 00:00:14,10/1/2016 00:16:02,460,Clark St & Bryn Mawr Ave,12150161,948,Customer

In [6]:
Divvy_Trips_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5954657 entries, 0 to 683831
Data columns (total 14 columns):
bikeid               int64
birthyear            float64
end_time             object
from_station_id      int64
from_station_name    object
gender               object
start_time           object
starttime            object
stoptime             object
to_station_id        int64
to_station_name      object
trip_id              int64
tripduration         int64
usertype             object
dtypes: float64(1), int64(5), object(8)
memory usage: 681.5+ MB

In [7]:
# Combine Stations Divvy Data File and store into Pandas DataFrame

In [8]:
# SQL Alchemy
from sqlalchemy import create_engine
# PyMySQL 
import pymysql
pymysql.install_as_MySQLdb()
#dialect+driver://username:password@host:port/database
engine = create_engine("mysql://nwds:asifroxmysox@mysql-divvy-taxi.cdxlmbtirvn0.us-east-2.rds.amazonaws.com:3306/transportation_db")
conn = engine.connect()

In [11]:
#write your data in // example from class except we set con=conn
Divvy_Trips_df.head().to_sql(name='TEST_Divvy_Trips', con=conn, if_exists='append', index=False)

In [12]:
#read the test table up there
pd.read_sql('SELECT * FROM TEST_Divvy_Trips', conn)

,bikeid,birthyear,end_time,from_station_id,from_station_name,gender,start_time,starttime,stoptime,to_station_id,to_station_name,trip_id,tripduration,usertype
0,3304,1988.0,1/1/2018 0:03,159,Claremont Ave & Hirsch St,Male,12/31/2017 23:58,None,None,69,Damen Ave & Pierce Ave,17536701,284,Subscriber
1,5975,NaN,1/1/2018 0:18,145,Mies van der Rohe Way & Chestnut St,None,12/31/2017 23:54,None,None,145,Mies van der Rohe Way & Chestnut St,17536700,1402,Customer
2,4906,NaN,1/1/2018 0:18,145,Mies van der Rohe Way & Chestnut St,None,12/31/2017 23:54,None,None,145,Mies van der Rohe Way & Chestnut St,17536699,1441,Customer
3,5667,1963.0,12/31/2017 23:53,340,Clark St & Wrightwood Ave,Male,12/31/2017 23:48,None,None,143,Sedgwick St & Webster Ave,17536698,315,Subscriber
4,5353,1977.0,12/31/2017 23:47,240,Sheridan Rd & Irving Park Rd,Male,12/31/2017 23:42,None,None,245,Clarendon Ave & Junior Ter,17536697,272,Subscriber

In [10]:
#read the test table up there
pd.read_sql('SELECT * FROM Divvy_Trips', conn)

,bikeid,birthyear,end_time,from_station_id,from_station_name,gender,start_time,starttime,stoptime,to_station_id,to_station_name,trip_id,tripduration,usertype
0,3304,1988.0,1/1/2018 0:03,159,Claremont Ave & Hirsch St,Male,12/31/2017 23:58,None,None,69,Damen Ave & Pierce Ave,17536701,284,Subscriber
1,5975,NaN,1/1/2018 0:18,145,Mies van der Rohe Way & Chestnut St,None,12/31/2017 23:54,None,None,145,Mies van der Rohe Way & Chestnut St,17536700,1402,Customer
2,4906,NaN,1/1/2018 0:18,145,Mies van der Rohe Way & Chestnut St,None,12/31/2017 23:54,None,None,145,Mies van der Rohe Way & Chestnut St,17536699,1441,Customer
3,5667,1963.0,12/31/2017 23:53,340,Clark St & Wrightwood Ave,Male,12/31/2017 23:48,None,None,143,Sedgwick St & Webster Ave,17536698,315,Subscriber
4,5353,1977.0,12/31/2017 23:47,240,Sheridan Rd & Irving Park Rd,Male,12/31/2017 23:42,None,None,245,Clarendon Ave & Junior Ter,17536697,272,Subscriber
5,5840,1988.0,12/31/2017 23:51,93,Sheffield Ave & Willow St,Male,12/31/2017 23:41,None,None,343,Racine Ave & Wrightwood Ave,17536696,589,Subscriber
6,6351,1990.0,12/31/2017 23:39,337,Clark St & Chicago Ave,Male,12/31/2017 23:34,None,None,182,Wells St & Elm St,17536695,301,Subscriber
7,2562,1987.0,12/31/2017 23:23,226,Racine Ave & Belmont Ave,Male,12/31/2017 23:21,None,None,117,Wilton Ave & Belmont Ave,17536694,141,Subscriber
8,2471,1981.0,12/31/2017 23:27,49,Dearborn St & Monroe St,Male,12/31/2017 23:17,None,None,26,McClurg Ct & Illinois St,17536693,615,Subscriber
9,6462,1980.0,12/31/2017 23:09,196,Cityfront Plaza Dr & Pioneer Ct,Male,12/31/2017 22:57,None,None,255,Indiana Ave & Roosevelt Rd,17536692,743,Subscriber
10,3775,1991.0,12/31/2017 22:53,59,Wabash Ave & Roosevelt Rd,Male,12/31/2017 22:50,None,None,72,Wabash Ave & 16th St,17536691,216,Subscriber
11,3663,1990.0,12/31/2017 22:53,59,Wabash Ave & Roosevelt Rd,Female,12/31/2017 22:50,None,None,72,Wabash Ave & 16th St,17536690,202,Subscriber
12,6456,1991.0,12/31/2017 22:55,475,Washtenaw Ave & Lawrence Ave,Male,12/31/2017 22:48,None,None,242,Damen Ave & Leland Ave,17536689,420,Subscriber
13,5529,1986.0,12/31/2017 22:51,67,Sheffield Ave & Fullerton Ave,Male,12/31/2017 22:45,None,None,166,Ashland Ave & Wrightwood Ave,17536688,397,Subscriber
14,3536,1988.0,12/31/2017 22:44,123,California Ave & Milwaukee Ave,Male,12/31/2017 22:42,None,None,259,California Ave & Francis Pl,17536687,137,Subscriber
15,3644,1961.0,12/31/2017 22:20,523,Eastlake Ter & Rogers Ave,Male,12/31/2017 22:09,None,None,447,Glenwood Ave & Morse Ave,17536686,677,Subscriber
16,2928,1992.0,12/31/2017 22:27,196,Cityfront Plaza Dr & Pioneer Ct,Male,12/31/2017 22:07,None,None,626,Delano Ct & Roosevelt Rd,17536685,1200,Subscriber
17,5889,1977.0,12/31/2017 22:12,293,Broadway & Wilson Ave,Male,12/31/2017 22:05,None,None,245,Clarendon Ave & Junior Ter,17536684,399,Subscriber
18,5960,1992.0,12/31/2017 22:11,510,Spaulding Ave & Division St,Male,12/31/2017 21:57,None,None,260,Kedzie Ave & Milwaukee Ave,17536683,845,Subscriber
19,3079,1988.0,12/31/2017 21:44,304,Broadway & Waveland Ave,Male,12/31/2017 21:42,None,None,232,Pine Grove Ave & Waveland Ave,17536680,86,Subscriber
20,1619,1990.0,12/31/2017 21:39,149,Calumet Ave & 33rd St,Male,12/31/2017 21:35,None,None,148,State St & 33rd St,17536675,263,Subscriber
21,5926,1977.0,12/31/2017 21:39,123,California Ave & Milwaukee Ave,Male,12/31/2017 21:34,None,None,290,Kedzie Ave & Palmer Ct,17536672,327,Subscriber
22,2928,1992.0,12/31/2017 21:49,211,St. Clair St & Erie St,Male,12/31/2017 21:33,None,None,196,Cityfront Plaza Dr & Pioneer Ct,17536671,969,Subscriber
23,3783,1995.0,12/31/2017 21:31,320,Loomis St & Lexington St,Male,12/31/2017 21:25,None,None,22,May St & Taylor St,17536653,339,Subscriber
24,4581,1964.0,12/31/2017 21:28,26,McClurg Ct & Illinois St,Male,12/31/2017 21:21,None,None,7,Field Blvd & South Water St,17536647,393,Subscriber
25,5667,1963.0,12/31/2017 21:22,143,Sedgwick St & Webster Ave,Male,12/31/2017 21:17,None,None,340,Clark St & Wrightwood Ave,17536645,303,Subscriber
26,3696,1989.0,12/31/2017 21:22,124,Damen Ave & Cullerton St,Male,12/31/2017 21:17,None,None,129,Blue Island Ave & 18th St,17536644,318,Subscriber
27,6189,NaN,12/31/2017 21:57,176,Clark St & Elm St,None,12/31/2017 21:16,None,None,37,Dearborn St & Adams St,17536643,2489,Customer
28,3777,1977.0,12/31/2017 21:10,91,Clinton St & Washington Blvd,Male,12/31/2017 21:08,None,None,66,Clinton St & Lake St,17536642,121,Subscriber
29,2928,1992.0,12/31/2017 21:33,46,Wells St & Walton St,Male,12/31/2017 21:05,None,None,211,St. Clair St & Erie St,17536641,1662,Subscriber
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,4310,1992.0,12/4/2017 11:21,109,900 W Harrison St,Male,12/4/2017 11:11,None,None,57,Clinton St & Roosevelt Rd,17412434,613,Subscriber
99971,3197,NaN,12/4/2017 12:03,35,Streeter Dr & Grand Ave,None,12/4/2017 11:10,None,None,35,Streeter Dr & Grand Ave,17412432,3179,Customer
99972,3797,1972.0,12/4/2017 11:18,176,Clark St & Elm St,Male,12/4/2017 11:10,None,None,48,Larrabee St & Kingsbury St,17412430,458,Subscriber
99973,237,1993.0,12/4/2017 11:28,127,Lincoln Ave & Fullerton Ave,Female,12/4/2017 11:10,None,None,291,Wells St & Evergreen Ave,17412428,1059,Subscriber
99974,5041,NaN,12/4/2017 12:02,35,Streeter Dr & Grand Ave,None,12/4/2017 11:10,None,None,35,Streeter Dr & Grand Ave,17412426,3126,Customer
99975,3962,1969.0,12/4/2017 11:18,51,Clark St & Randolph St,Male,12/4/2017 11:10,None,None,75,Canal St & Jackson Blvd,17412423,509,Subscriber
99976,2558,1990.0,12/4/2017 11:16,307,Southport Ave & Clybourn Ave,Male,12/4/2017 11:10,None,None,113,Bissell St & Armitage Ave,17412421,371,Subscriber
99977,2058,1958.0,12/4/2017 11:40,39,Wabash Ave & Adams St,Male,12/4/2017 11:10,None,None,341,Adler Planetarium,17412420,1841,Subscriber
99978,3413,NaN,12/4/2017 11:25,284,Michigan Ave & Jackson Blvd,None,12/4/2017 11:09,None,None,3,Shedd Aquarium,17412417,946,Customer
99979,5938,1989.0,12/4/2017 11:15,229,Southport Ave & Roscoe St,Female,12/4/2017 11:09,None,None,319,Greenview Ave & Diversey Pkwy,17412415,344,Subscriber
99980,6298,1996.0,12/4/2017 11:13,22,May St & Taylor St,Male,12/4/2017 11:09,None,None,32,Racine Ave & Congress Pkwy,17412413,242,Subscriber
99981,590,1969.0,12/4/2017 11:17,286,Franklin St & Quincy St,Male,12/4/2017 11:09,None,None,321,Wabash Ave & 9th St,17412410,518,Subscriber
99982,1314,1958.0,12/4/2017 11:13,153,Southport Ave & Wellington Ave,Male,12/4/2017 11:09,None,None,131,Lincoln Ave & Belmont Ave,17412409,253,Subscriber
99983,3826,NaN,12/4/2017 11:25,284,Michigan Ave & Jackson Blvd,None,12/4/2017 11:09,None,None,3,Shedd Aquarium,17412406,990,Customer
99984,5165,1988.0,12/4/2017 11:21,51,Clark St & Randolph St,Male,12/4/2017 11:08,None,None,142,McClurg Ct & Erie St,17412404,735,Subscriber
99985,4403,1989.0,12/4/2017 11:31,52,Michigan Ave & Lake St,Male,12/4/2017 11:08,None,None,98,LaSalle St & Washington St,17412402,1363,Subscriber
99986,2308,1963.0,12/4/2017 11:14,283,LaSalle St & Jackson Blvd,Male,12/4/2017 11:08,None,None,283,LaSalle St & Jackson Blvd,17412401,331,Subscriber
99987,5751,NaN,12/4/2017 11:39,49,Dearborn St & Monroe St,None,12/4/2017 11:08,None,None,3,Shedd Aquarium,17412400,1852,Customer
99988,2116,NaN,12/4/2017 11:37,49,Dearborn St & Monroe St,None,12/4/2017 11:08,None,None,3,Shedd Aquarium,17412398,1749,Customer
99989,886,1983.0,12/4/2017 11:25,27,Larrabee St & North Ave,Male,12/4/2017 11:08,None,None,127,Lincoln Ave & Fullerton Ave,17412397,1033,Subscriber
99990,801,1995.0,12/4/2017 11:15,48,Larrabee St & Kingsbury St,Male,12/4/2017 11:08,None,None,106,State St & Pearson St,17412395,421,Subscriber
99991,4769,1958.0,12/4/2017 11:18,264,Stetson Ave & South Water St,Male,12/4/2017 11:08,None,None,211,St. Clair St & Erie St,17412394,604,Subscriber
99992,2347,1985.0,12/4/2017 11:13,217,Racine Ave (May St) & Fulton St,Male,12/4/2017 11:08,None,None,198,Green St & Madison St,17412392,309,Subscriber
99993,5335,NaN,12/4/2017 11:26,62,McCormick Place,None,12/4/2017 11:07,None,None,97,Field Museum,17412389,1133,Customer
99994,6429,1997.0,12/4/2017 11:17,40,LaSalle St & Adams St,Female,12/4/2017 11:07,None,None,31,Franklin St & Chicago Ave,17412385,607,Subscriber
99995,3218,1985.0,12/4/2017 11:27,212,Orleans St & Ohio St,Male,12/4/2017 11:07,None,None,113,Bissell St & Armitage Ave,17412384,1181,Subscriber
99996,2651,NaN,12/4/2017 11:26,62,McCormick Place,None,12/4/2017 11:07,None,None,97,Field Museum,17412383,1153,Customer
99997,5966,1957.0,12/4/2017 11:27,257,Lincoln Ave & Waveland Ave,Male,12/4/2017 11:06,None,None,153,Southport Ave & Wellington Ave,17412380,1243,Subscriber
99998,2924,1990.0,12/4/2017 11:13,140,Dearborn Pkwy & Delaware Pl,Male,12/4/2017 11:06,None,None,38,Clark St & Lake St,17412378,469,Subscriber
99999,3536,NaN,12/4/2017 11:15,35,Streeter Dr & Grand Ave,None,12/4/2017 11:05,None,None,133,Kingsbury St & Kinzie St,17412377,582,Customer

In [9]:
# #read the test table up there
# pd.read_sql('SELECT * FROM test_table', conn)

#write your data in // example from class except we set con=conn
Divvy_Trips_df.head(100000).to_sql(name='Divvy_Trips', con=conn, if_exists='replace', index=False)