In [1]:
#!/usr/bin/env python

# make sure to install these packages before running:
#!pip install pandas
#!pip install sodapy

import pandas as pd
from sodapy import Socrata
import numpy as np
import requests

In [47]:
select = [ 'dropoff_census_tract', 
       'dropoff_community_area', 
       'pickup_census_tract', 
       'pickup_community_area', 
       'trip_end_timestamp', 'trip_id', 'trip_miles', 'trip_seconds',
       'trip_start_timestamp', 'trip_total']
select_string = ""
for cat in select:
    select_string += cat
    if select[-1]  != cat:
        select_string += ', '
select_string

'dropoff_census_tract, dropoff_community_area, pickup_census_tract, pickup_community_area, trip_end_timestamp, trip_id, trip_miles, trip_seconds, trip_start_timestamp, trip_total'

In [52]:
#https://data.cityofchicago.org/resource/wrvz-psew.json?trip_start_timestamp=2017-01-01T16:45:00.000&
            
  
# Example authenticated client (needed for non-public datasets):
client = Socrata("data.cityofchicago.org",
                 "FV1cGhyB0xdI4IWhANhtkk3Cz")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("wrvz-psew", where="trip_start_timestamp between '2016-09-01' and '2017-09-01' and dropoff_community_area<>76 and pickup_community_area <> 76 ",
                    select=select_string ,limit=1000000)


# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)   
results_df.head()

,dropoff_census_tract,dropoff_community_area,pickup_census_tract,pickup_community_area,trip_end_timestamp,trip_id,trip_miles,trip_seconds,trip_start_timestamp,trip_total
0,17031081401,8,17031281900,28,2017-03-06T07:45:00.000,48f6e83845fa071725402a040b35e8fd940c9aa9,2.1,780,2017-03-06T07:30:00.000,9.75
1,17031081403,8,17031320100,32,2017-05-27T15:45:00.000,48f6f2465d259e4c063262798d244aea80aaa66f,0.6,240,2017-05-27T15:45:00.000,5.25
2,NaN,4,NaN,8,2017-04-28T02:15:00.000,48f6fd0ac80be2f7dd2fde6ffc71e0ba76e56014,8.5,1080,2017-04-28T01:45:00.000,30.55
3,17031281900,28,17031081500,8,2017-04-30T18:45:00.000,48f8abc927e87a7aa3e2ed87783f63b94ebbb126,1.53,541,2017-04-30T18:45:00.000,8.75
4,17031839100,32,17031081201,8,2017-05-28T14:30:00.000,48f8f518c055dc33397b9f95f53d29bf1b0c0f31,2.58,1140,2017-05-28T14:00:00.000,12

In [1]:
#help(client.get)

In [50]:
results_df.columns

Index(['dropoff_census_tract', 'dropoff_community_area', 'pickup_census_tract',
       'pickup_community_area', 'trip_end_timestamp', 'trip_id', 'trip_miles',
       'trip_seconds', 'trip_start_timestamp', 'trip_total'],
      dtype='object')

In [53]:
#drop NA
results=results_df.dropna(axis=0)
results.head()
len(results)

695369

In [32]:
#drop unnessasry columns
#remove_columns_results_df=results.drop(columns=['company', 'extras', 'fare', 'payment_type','taxi_id', 'tips', 'tolls'])
#len(remove_columns_results_df)

1000

In [60]:
results_census_tract = client.get("wrvz-psew", where="trip_start_timestamp between '2016-09-01' and '2017-09-01' and dropoff_community_area<>76 and pickup_community_area <> 76 ",
                     limit=1000)

In [69]:
census_track_df = pd.DataFrame.from_records(results_census_tract)

In [70]:
census_track_df.columns

Index(['dropoff_census_tract', 'dropoff_centroid_latitude',
       'dropoff_centroid_longitude', 'dropoff_community_area'],
      dtype='object')

In [95]:
ct_sel = 'distinct dropoff_census_tract, dropoff_centroid_latitude, dropoff_centroid_longitude, dropoff_community_area'

In [90]:
track_df_clean =census_track_df.dropna(axis=0)

In [91]:
track_df_clean.sort_values('dropoff_census_tract')

,dropoff_census_tract,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_community_area
780,17031032100,41.958154876,-87.653021789,3
615,17031060800,41.953400044,-87.646007066,6
248,17031061902,41.943155086,-87.640698076,6
850,17031062000,41.942577185,-87.647078509,6
347,17031062100,41.942691844,-87.651770507,6
31,17031062100,41.942691844,-87.651770507,6
755,17031062100,41.942691844,-87.651770507,6
552,17031062100,41.942691844,-87.651770507,6
812,17031062900,41.936237179,-87.656411531,6
349,17031063100,41.938232293,-87.646782081,6
576,17031063200,41.938391258,-87.63857492,6
889,17031063301,41.934539716,-87.643022804,6
986,17031063302,41.934762456,-87.639853859,6
492,17031063302,41.934762456,-87.639853859,6
274,17031063302,41.934762456,-87.639853859,6
795,17031063400,41.934659157,-87.646729729,6
624,17031070101,41.92926299,-87.635890954,7
815,17031070101,41.92926299,-87.635890954,7
746,17031070101,41.92926299,-87.635890954,7
132,17031070101,41.92926299,-87.635890954,7
882,17031070102,41.93057857,-87.642206313,7
744,17031070102,41.93057857,-87.642206313,7
268,17031070200,41.929077655,-87.646293476,7
906,17031070200,41.929077655,-87.646293476,7
573,17031070200,41.929077655,-87.646293476,7
310,17031070300,41.929046937,-87.651310877,7
862,17031070300,41.929046937,-87.651310877,7
322,17031070400,41.928967266,-87.656156831,7
639,17031070500,41.928945904,-87.66089257,7
698,17031070600,41.928763006,-87.665676837,7
...,...,...,...,...
278,17031839100,41.880994471,-87.632746489,32
829,17031839100,41.880994471,-87.632746489,32
176,17031839100,41.880994471,-87.632746489,32
183,17031839100,41.880994471,-87.632746489,32
275,17031839100,41.880994471,-87.632746489,32
719,17031839100,41.880994471,-87.632746489,32
375,17031841000,41.849246754,-87.624135298,33
945,17031841000,41.849246754,-87.624135298,33
834,17031841900,41.867902418,-87.642958665,28
250,17031841900,41.867902418,-87.642958665,28
391,17031841900,41.867902418,-87.642958665,28
778,17031841900,41.867902418,-87.642958665,28
134,17031842200,41.904935302,-87.649907226,8
502,17031842200,41.904935302,-87.649907226,8
239,17031842200,41.904935302,-87.649907226,8
764,17031842200,41.904935302,-87.649907226,8
936,17031842200,41.904935302,-87.649907226,8
638,17031842200,41.904935302,-87.649907226,8
35,17031842300,41.89830587,-87.653613982,24
38,17031842300,41.89830587,-87.653613982,24
939,17031842300,41.89830587,-87.653613982,24
724,17031842300,41.89830587,-87.653613982,24
343,17031842300,41.89830587,-87.653613982,24
260,17031843700,41.944813754,-87.69077501,5
426,17031980100,41.785998518,-87.750934289,56
855,17031980100,41.785998518,-87.750934289,56
726,17031980100,41.785998518,-87.750934289,56
283,17031980100,41.785998518,-87.750934289,56
117,17031980100,41.785998518,-87.750934289,56
305,17031980100,41.785998518,-87.750934289,56